import os
import torch
from io import BytesIO
import json
from fastapi import FastAPI
from diffusers import StableDiffusionPipeline
from pyrogram import Client, filters
from PIL import Image

# =============== CONFIG ===============
BOT_TOKEN = os.getenv("BOT_TOKEN")
API_ID = int(os.getenv("API_ID", "123456"))  # Fill from my.telegram.org
API_HASH = os.getenv("API_HASH", "0123456789abcdef0123456789abcdef")

# =============== FASTAPI SERVER ===============
app = FastAPI()

@app.get("/")
def home():
    return {"status": "running", "message": "Prompt-to-Image Generator is Live!"}

# =============== LOAD MODEL ===============
print("🔄 Loading Stable Diffusion model... This may take 1–2 minutes.")
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float32
)
pipe.to("cpu")
print("✅ Model Loaded Successfully.")

# =============== TELEGRAM BOT ===============
bot = Client("Prompt2ImageBot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)


# ======= JSON Prompt Understanding =======
def parse_prompt(user_prompt: str):
    """
    User ke prompt ko JSON-style mein convert karta hai taaki
    AI image zyada accurate aur artistic bane.
    """
    try:
        return {
            "scene": user_prompt,
            "subject": "main focus of prompt",
            "style": "ultra realistic, 4k, cinematic lighting, masterpiece, detailed"
        }
    except Exception:
        return {"scene": user_prompt, "subject": "art", "style": "beautiful and colorful"}


# ======= START COMMAND =======
@bot.on_message(filters.command("start"))
async def start(_, message):
    await message.reply_text(
        "👋 *नमस्ते!* मैं एक AI Image Generator Bot हूँ.\n"
        "मुझे कोई भी *prompt* भेजो और मैं उसी हिसाब से शानदार image बना दूँ।\n\n"
        "🧠 उदाहरण:\n"
        "`एक पहाड़ के ऊपर उगता सूरज`\n"
        "`A futuristic cyberpunk city at night`\n\n"
        "⚙️ मैं JSON prompt समझकर जादू करता हूँ 😉"
    )


# ======= IMAGE GENERATION =======
@bot.on_message(filters.text & ~filters.command("start"))
async def generate_image(_, message):
    prompt_text = message.text.strip()

    if len(prompt_text) < 3:
        await message.reply_text("❗ कृपया थोड़ा बड़ा prompt भेजें ताकि मैं बेहतर image बना सकूँ।")
        return

    await message.reply_text("🎨 Prompt को समझ रहा हूँ और AI image बना रहा हूँ... कृपया इंतज़ार करें।")

    prompt_json = parse_prompt(prompt_text)

    full_prompt = (
        f"{prompt_json['scene']}, "
        f"{prompt_json['subject']}, "
        f"{prompt_json['style']}"
    )

    print(f"🧠 Final Prompt Used: {full_prompt}")

    try:
        image = pipe(full_prompt).images[0]
        bio = BytesIO()
        bio.name = "result.png"
        image.save(bio, "PNG")
        bio.seek(0)

        await message.reply_photo(
            photo=bio,
            caption=f"🖼 Prompt: `{prompt_text}`\n🤖 Generated by AI Model (Stable Diffusion)"
        )

        del image
    except Exception as e:
        await message.reply_text(f"⚠️ Error: {str(e)}")


# ======= RUN BOTH (FASTAPI + BOT) =======
if __name__ == "__main__":
    import threading
    import uvicorn

    def run_fastapi():
        uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8080)))

    threading.Thread(target=run_fastapi).start()
    print("🚀 Telegram Bot Started Successfully!")
    bot.run()
